package com.stamping.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import com.fasterxml.jackson.annotation.JsonInclude;

import java.util.Map;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class TemplateRequest {

    private String publisherId;
    private String jcode;
    private String templateName;

    /**
     * Shortcode key-value pairs, e.g. {"LOGO_TEXT": "AJNR", "ARTICLE_TITLE": "..."}
     */
    private Map<String, String> shortcodes;

    /** The full HTML template with {{SHORTCODE}} placeholders */
    private String htmlTemplate;

    /** The resolved HTML with shortcodes replaced (generated by frontend) */
    private String resolvedHtml;
}
